name: CD

on:
  release:
    types:
    - created
env:
  PROJECT_PATH: 'Paytrail-dotnet-sdk/Paytrail-dotnet-sdk.csproj'
  NUGET_API_KEY: 'oy2nr6qorpnv64awjhcacxyib7p5sjrenoe5uvofap3zoa'

jobs:
  deploy:
    name: Publish Nuget
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    
    - name: Get Version
      id: version
      uses: battila7/get-version-action@v2

    # Publish
    - name: Publish NuGet
      id: publish_nuget
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: ${{ env.PROJECT_PATH }}
        # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
        VERSION_STATIC: ${{ steps.version.outputs.version }}

        # API key to authenticate with NuGet server
        NUGET_KEY: ${{env.NUGET_API_KEY}}
