# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore Paytrail-dotnet-sdk/Paytrail-dotnet-sdk.csproj
      
    - name: Build
      run: dotnet build Paytrail-dotnet-sdk/Paytrail-dotnet-sdk.csproj --no-restore --configuration Release
   
    - name: Test
      run: dotnet test Paytrail-dotnet-sdk.UnitTest/Paytrail-dotnet-sdk.UnitTest.csproj --configuration release --no-build --verbosity 

      
    - name: publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Paytrail-dotnet-sdk/Paytrail-dotnet-sdk.csproj
        NUGET_KEY: oy2nr6qorpnv64awjhcacxyib7p5sjrenoe5uvofap3zoa
        NUGET_SOURCE: https://api.nuget.org/v3/index.json
        VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
        
